<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Render\Element;

/**
 * @file
 * Contains functions for demo module.
 */

/**
 * Manually set path aliases.
 */
function demo_set_path_aliases() {
  $storage = \Drupal::entityTypeManager()->getStorage('node');

  $mapping = [
    'Accueil'                    => '/accueil',
    '403'                        => '/403',
    '404'                        => '/404',
    'Page en FR'                 => '/page-fr',
    'Page in EN'                 => '/page-en',
    'Pagina in ES'               => '/page-es',
    'Page langue non specifiee'  => '/page-und',
    'Page langue non applicable' => '/page-xxx',
  ];

  foreach ($mapping as $label => $path) {
    $nodes = $storage->loadByProperties(['title' => $label]);
    foreach ($nodes as $node) {
      $node->set('path', $path);
      $node->save();
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_view_alter() for paragraphs.
 */
function demo_paragraph_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->bundle() == 'menu') {
    if (function_exists('menu_manipulator_get_multilingual_menu')) {
      foreach (Element::children($build['field_menu']) as $i) {
        $menu_name               = $entity->get('field_menu')->get($i)->getString();
        $build['field_menu'][$i] = menu_manipulator_get_multilingual_menu($menu_name);
      }
    }
  }
}
